export type Screen = 
  | "splash"
  | "home"
  | "gacha"
  | "collection"
  | "ranking"
  | "training"
  | "matchmaking"
  | "battle"
  | "battle-royale"
  | "team-royale"
  | "boss-select"
  | "boss-raid"
  | "tutorial"
  | "profile"
